postgres: &postgres
  adapter: postgresql
  host:  <%= ENV['PG_HOST'] %>
  port:  <%= ENV['PG_PORT'] %>
  encoding: <%= ENV['PG_ENCODING'] %>
  database: <%= ENV['PG_NAME'] %>
  pool: <%= ENV['PG_POOL'] %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>

sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  database: db/database.sqlite3
  timeout: 5000

development:
  <<: *postgres

test:
  <<: *sqlite

production:
  <<: *sqlite
